spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
